### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by Bernardopog** [codebyveronica/FAQ-accordion#1]
Olá Veronica, sou o Bernardo do Frontend Mentor.

Optei por refazer parte do seu projeto, alterando apenas o HTML e JS, para demonstrar uma segunda forma de trabalhar com o JS e HTML de forma mais performática e dentro das boas práticas.

[Código Alterado](https://github.com/R3ygoski/veronica-faq-challenge) <-- Para poder comparar ambos os códigos.
[Página](https://r3ygoski.github.io/veronica-faq-challenge/) <-- Para ver o resultado

As alterações que fiz no HTML foram focadas na remoção dos `id` repetidos. Repetir id's é uma má prática, e deve ser evitado a todo custo. Id's devem sempre ser únicos. Então para evitar essa má prática eu optei por alterar todos `id` para `data-attribute`, porque dessa forma você teria um valor que poderia se repetir e não causaria nenhum problema.

Já no JS eu alterei a parte lógica, tanto que da forma que você havia feito, você não estava apagando as `<img/>` e isso fazia com que elas ainda existissem dentro do DOM, mesmo se não estivessem aparecendo, veja:

![image](https://github.com/user-attachments/assets/129508d2-5a64-4fb2-af76-09297aed7bfd)

E isso não é recomendado, então alterei para que houvesse apenas uma `<img/>` no HTML, e que o atributo dela fosse alterado entre o símbolo de menos e o de mais.

Também alterei a parte de selecionar o elemento pai do botão, isso porque você utilizou o método `closest`, isso pode trazer uma performance ruim para seu projeto devido ao fato de ter que percorrer a árvore do DOM para encontrar o elemento mais próximo do selecionado. Por causa disso alterei para a propriedade `parentNode`, porquê dessa forma ele já seleciona o elemento pai diretamente.

E é isso, parabéns pela conclusão do projeto, qualquer dúvida quanto ao que eu disse, por favor responda aqui no Github ou lá no Frontend Mentor, que tentarei ajudar assim que possível.

**Comment by codebyveronica** [comment]
Olá Bernardo, muito obrigada! É ótimo receber um feedback construtivo como esse! Eu tentei como pude chegar no resultado proposto, e o ID duplicado acabou sendo uma falta de atenção minha, com certeza vou evitar repetir isso no futuro. Muito obrigada por me mostrar uma forma melhor de resolução pra esse projeto. Inicialmente, eu tentei fazer mudando somente o src da img, mas simplesmente não conseguia o resultado, então agora ver funcionando é ótimo. Obrigada mesmo!
